import discontinuous_ordinary_differential_equations_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace discontinuous_ordinary_differential_equations_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end discontinuous_ordinary_differential_equations_theorem_canonical_lane_mathlib
end HautevilleHouse
